### ISSUE TITLE
package Windows as an exe

### ISSUE THREAD

**Issue by oakmac** [oakmac/cuttle#64]
Use [NSIS](http://nsis.sourceforge.net/Main_Page) to package the Windows releases.

**Comment by CASandmann** [comment]
So this was actually pretty simple due to a couple things:

There is a [NSIS editor](http://hmne.sourceforge.net/) that allows for extremely quick creation of .nsi scripts via a wizard.  I messed up because I added the files to the path as a group and then added subdirectories using the "add file tree" button which didn't include the root directories I added.  Just add the whole output folder as a file tree (for future reference).  Also, make sure you use relative paths >.<

The second thing is what makes this .exe creator so beautiful.  If you [download NSIS](http://nsis.sourceforge.net/Download) then add the directory to your PATH, you can call `makensis` and pass in exe_script.nsi as an argument.  This generates the installer.  I made the release script move the .exe into the builds/ folder when it's complete as to not clutter up the main directory.  I didn't have time to figure out how to make certain fields in the .nsi script dynamic, so we'll have to manually edit e.g. the version number until I do.

**Comment by CASandmann** [comment]
I don't know how to GitHub.  Closed with commit [8b2fb9d](https://github.com/oakmac/cuttle/commit/95e79a7aaf162b2ec2911a31c186a70cd57513d0).
